### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by gaby** [jpetrucciani/ruff-check#37]
Hello @jpetrucciani I noticed the examples are using @main would it be possible to create tags for each new ruff release? The latest current tag is several months old

**Comment by gaby** [comment]
Nevermind, just noticed you are creating tags :-) thanks!

**Comment by jpetrucciani** [comment]
Yep, no worries! If you have any links on how to create the "releases" automatically as well, that would solve the visibility problem! Not sure if I just haven't searched around enough, or if it's just not possible 🤔
