### ISSUE TITLE
Unexpected argument '--format' found caused by upgrading Ruff to latest version

### ISSUE THREAD

**Issue by lextoumbourou** [jpetrucciani/ruff-check#62]
Hi team, about 7 hours ago Ruff was updated to the latest version: https://github.com/jpetrucciani/ruff-check/commit/fbcc7f8ec57b44548034d0cf4542b91904f2fc26

However, Ruff removed support for the `--format` argument breaking the latest version of this action: https://github.com/astral-sh/ruff/pull/7984

We get this error in all our actions that use this check:

```
+ ruff --version
+ ruff --format github '--ignore=E402' --fix '--line-length=90' text2song-service/
ruff 0.1.0
error: unexpected argument '--format' found
```

Proposed fix. Either:
- lock version of Ruff to previous version
- migrate to new flag.

Thanks for making this action!

**Comment by jpetrucciani** [comment]
Thanks for the note! I'll get this fixed up and re-tagged

**Comment by jpetrucciani** [comment]
`@main` and `@0.1.0` both should now be fixed up with the new flag!
